name: esm2
channels:
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pytorch>=2.5.0
  - torchvision>=0.20.0
  - torchaudio>=2.5.0
  - pytorch-cuda=12.4
  - numpy>=2.0.0
  - pandas>=2.3.0
  - scipy>=1.13.0
  - scikit-learn>=1.6.0
  - imbalanced-learn>=0.12.0
  - scikit-optimize>=0.10.0
  - umap-learn>=0.5.9
  - matplotlib-base>=3.9.0
  - seaborn>=0.13.0
  - networkx>=3.2.0
  - kahip>=3.18
  - tqdm>=4.67.0
  - setuptools
  - wheel
  - pip
  - mkl>=2023.2.0
  - mkl-devel
  - intel-openmp
  - openssl
  - ca-certificates
  - certifi
  
  - pip:
    # Transformers
    - transformers>=4.49.0
    - tokenizers>=0.21.0
    - datasets>=3.5.0
    - accelerate>=1.6.0
    - safetensors>=0.5.0
    
    # LoRA/PEFT
    - peft>=0.15.0
    
    - fair-esm>=2.0.0
    - biopython>=1.85
    - huggingface-hub>=0.29.0
    
    - pytorch-lightning>=2.5.0
    - torchmetrics>=1.8.0
    - einops>=0.8.0
    - omegaconf>=2.3.0
